#!/bin/bash

if [ ! -z "${QUERY_STRING:-}" ]; then
  camera=$(echo "$QUERY_STRING" | sed 's/.*camera=\([^&]*\).*/\1/')
  if [ "${camera}" = "${QUERY_STRING}" ]; then camera=; fi
fi

if [ ! -z "${QUERY_STRING:-}" ]; then
  id=$(echo "$QUERY_STRING" | sed 's/.*id=\([^&]*\).*/\1/')
  if [ "${id}" = "${QUERY_STRING}" ]; then id=; fi
fi

file=

if [ ! -z "${id:-}" ]; then
  file=$(mktemp)
  ./bin/jpg.sh ${camera:-} ${id} > ${file}

  if [ -s "${file}" ]; then
    echo "Content-Type: image/jpg"
    echo "Access-Control-Allow-Origin: *"
    echo "Cache-Control: no-cache"
    echo "Cache-Control: max-age=30"
    echo ""
    cat ${file}
  fi
fi

if [ -z "${file:-}" ] || [ ! -s "${file}" ]; then
  echo "Content-Type: application/json; charset=utf-8"
  echo "Access-Control-Allow-Origin: *"
  echo "Cache-Control: no-cache"
  echo "Cache-Control: max-age=30"
  echo ""
  echo '{"request":"'${id:-}'","camera":"'${camera:-}'","error":"not found"}'
fi

if [ ! -z "${file:-}" ]; then rm -f "${file}"; fi
