#!/bin/bash

if [ ! -z "${QUERY_STRING:-}" ]; then
  camera=$(echo "$QUERY_STRING" | sed 's/.*camera=\([^&]*\).*/\1/')
  if [ "${camera}" = "${QUERY_STRING}" ]; then camera=; fi
fi

if [ ! -z "${QUERY_STRING:-}" ]; then
  id=$(echo "$QUERY_STRING" | sed 's/.*id=\([^&]*\).*/\1/')
  if [ "${id}" = "${QUERY_STRING}" ]; then id=; fi
fi

if [ ! -z "${QUERY_STRING:-}" ]; then
  event=$(echo "$QUERY_STRING" | sed 's/.*event=\([^&]*\).*/\1/')
  if [ "${event}" != "${QUERY_STRING}" ]; then id='[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-'"${event}"; fi
fi

if [ ! -z "${QUERY_STRING:-}" ]; then
  file=$(echo "$QUERY_STRING" | sed 's/.*file=\([^&]*\).*/\1/')
  if [ "${file}" != "${QUERY_STRING}" ]; then id="${file}"; fi
fi

temp=

if [ ! -z "${id:-}" ]; then
  temp=$(mktemp)
  ./bin/mp4.sh "${camera:-}" "${id}" > ${temp}

  if [ -s "${temp}" ]; then
    echo "Content-Type: image/mp4"
    echo "Access-Control-Allow-Origin: *"
    echo "Cache-Control: no-cache"
    echo "Cache-Control: max-age=30"
    echo ""
    cat ${temp}
  fi
fi

if [ -z "${temp:-}" ] || [ ! -s "${temp}" ]; then
  echo "Content-Type: application/json; charset=utf-8"
  echo "Access-Control-Allow-Origin: *"
  echo "Cache-Control: no-cache"
  echo "Cache-Control: max-age=30"
  echo ""
  echo '{"request":"'${id:-}'","camera":"'${camera:-}'","error":"not found"}'
fi

if [ ! -z "${temp:-}" ]; then rm -f "${temp}"; fi
